-- System B (Oracle) schema
-- Tables: B_ACCOUNT, B_STUDENT, B_COURSE, B_CHOICE
--         B_CROSS_CHOICE (mirror records for cross-department selections)

-- Make schema idempotent for repeated runs.
-- We rely on spring.sql.init.continue-on-error=true to ignore ORA-00942.
DROP TABLE B_CHOICE CASCADE CONSTRAINTS;
DROP TABLE B_CROSS_CHOICE CASCADE CONSTRAINTS;
DROP TABLE B_ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE B_COURSE CASCADE CONSTRAINTS;
DROP TABLE B_STUDENT CASCADE CONSTRAINTS;

CREATE TABLE B_STUDENT (
  SNO    VARCHAR2(9)   PRIMARY KEY,
  SNM    VARCHAR2(20 CHAR)  NOT NULL,
  SEX    VARCHAR2(6 CHAR)   NOT NULL,
  MAJOR  VARCHAR2(32 CHAR)  NOT NULL,
  PHONE  VARCHAR2(20),
  EMAIL  VARCHAR2(64),
  PWD    VARCHAR2(6)   NOT NULL,
  ORIGIN VARCHAR2(1)   DEFAULT 'B' NOT NULL
);

CREATE TABLE B_ACCOUNT (
  ACC   VARCHAR2(12) PRIMARY KEY,
  PASS  VARCHAR2(12) NOT NULL,
  LVL   NUMBER(2)    NOT NULL,
  OBJ   VARCHAR2(9),
  CONSTRAINT FK_B_ACCOUNT_STUDENT FOREIGN KEY (OBJ) REFERENCES B_STUDENT(SNO)
);

CREATE TABLE B_COURSE (
  CNO    VARCHAR2(5)  PRIMARY KEY,
  CNM    VARCHAR2(16) NOT NULL,
  CTM    VARCHAR2(2)  NOT NULL,
  CPT    VARCHAR2(1)  NOT NULL,
  TEC    VARCHAR2(10) NOT NULL,
  PLA    VARCHAR2(20) NOT NULL,
  SHARE_FLAG  CHAR(1)      DEFAULT '0' NOT NULL
);

CREATE TABLE B_CHOICE (
  CNO  VARCHAR2(5) NOT NULL,
  SNO  VARCHAR2(9) NOT NULL,
  GRD  VARCHAR2(3),
  CONSTRAINT PK_B_CHOICE PRIMARY KEY (CNO, SNO),
  CONSTRAINT FK_B_CHOICE_COURSE FOREIGN KEY (CNO) REFERENCES B_COURSE(CNO),
  CONSTRAINT FK_B_CHOICE_STUDENT FOREIGN KEY (SNO) REFERENCES B_STUDENT(SNO)
);

CREATE TABLE B_CROSS_CHOICE (
  CNO          VARCHAR2(5)   NOT NULL,
  SNO          VARCHAR2(9)   NOT NULL,
  CNM          VARCHAR2(16)  NOT NULL,
  CTM          VARCHAR2(2)   NOT NULL,
  CPT          VARCHAR2(1)   NOT NULL,
  TEC          VARCHAR2(10)  NOT NULL,
  PLA          VARCHAR2(20)  NOT NULL,
  SHARE_FLAG   CHAR(1)       DEFAULT '1' NOT NULL,
  DEST_SYSTEM  VARCHAR2(1)   NOT NULL,
  GRD          VARCHAR2(3),
  CONSTRAINT PK_B_CROSS_CHOICE PRIMARY KEY (CNO, SNO, DEST_SYSTEM)
);

